apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: hml
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>hml NGINX</title></head>
    <body><h1>🚀 NGINX rodando no ambiente de homologacao </h1></body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hml
  namespace: hml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hml
  template:
    metadata:
      labels:
        app: nginx-hml
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: nginx-index-html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hml
  namespace: hml
spec:
  selector:
    app: nginx-hml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hml
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-publico
  rules:
    - host: hml-devopslabs.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-hml
                port:
                  number: 80
