apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-hml
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brunobaltazar/kubernets_app.git
    targetRevision: main
    path: kube-prometheus-stack             # ✅ Corrigido
    helm:
      valueFiles:
        - hml-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false         # ❗ Não remove recursos que estão fora do Git — importante para preservar o namespace "hml"
      selfHeal: true       # ✅ Repara recursos automaticamente se forem modificados fora do Argo

    syncOptions:
      - CreateNamespace=true  # ✅ Cria o namespace automaticamente se ele ainda não existir (não afeta namespace já existente)

