grafana:
  enabled: true  # Ativa o Grafana como parte da stack

  ingress:
    enabled: true  # Ativa Ingress para acessar o Grafana via domínio
    ingressClassName: nginx-internet
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - grafana-hml.devopslabs.org
    path: /
    pathType: Prefix

  service:
    type: ClusterIP

  persistence:
    enabled: false  # ❌ DESATIVADO: evita erro de PVC até resolver problemas com storageClass ou login no ArgoCD

  adminPassword: "admin"  # ⚠️ Use um Secret externo em produção

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}

    # ❌ DESATIVADO: Removido para evitar erro de PVC
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: gp2
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 10Gi

alertmanager:
  enabled: false
  ingress:
    enabled: false
